spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB  # 파일 크기 제한 (10MB로 설정)
      max-request-size: 10MB  # 전체 요청 크기 제한 (10MB로 설정)

  jackson:
    time-zone: Asia/Seoul

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}

openai:
  api:
    model: gpt-4o
    base-url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/oauth/callback/kakao
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/oauth/callback/google
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:5173/oauth/callback/naver

# 선택사항: 서버 시간대도 설정 (스프링 부트 2.x 이하에서는 일부 경우 필요)
server:
  timezone: Asia/Seoul